######################################################################
# Automatically generated by qmake (3.0) Sat Aug 10 17:20:09 2019
######################################################################

TEMPLATE = app
TARGET = Display_simulator
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += sources/graph.h \
    sources/controlpanel.h
SOURCES += Display_simulator.cpp

FORMS +=
